# Generated by Django 5.2.18 on 2026-10-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('chapters', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('want_to_read', 'Want to read'), ('reading', 'Reading'), ('finished', 'Finished')], default='want_to_read', max_length=20)),
                ('format', models.CharField(choices=[('physical', 'Physical'), ('digital', 'Digital')], max_length=10)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, choices=[('manga', 'Manga'), ('manhwa', 'Manhwa'), ('webtoon', 'Webtoon'), ('novel', 'Novel'), ('fanfic', 'Fanfic'), ('other', 'Other')], max_length=20)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
