# Generated by Django 5.2.18 on 2026-10-07 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTrack', '0002_alter_newbook_options_alter_newbook_chapters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='publication_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('hiatus', 'On hiatus')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='newbook',
            name='chapters',
            field=models.IntegerField(blank=True, help_text='Total de capítulos. Se a obra está em lançamento, informe quantos já saíram.', null=True),
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_chapter', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='ReadTrack.newbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reading progress',
                'constraints': [models.UniqueConstraint(fields=('user', 'book'), name='unique_progress')],
            },
        ),
    ]
