# Generated by Django 5.2.18 on 2026-10-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTrack', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbook',
            name='content_type',
            field=models.CharField(blank=True, choices=[('manga', 'Mangá'), ('manhwa', 'Manhwa'), ('webtoon', 'Webtoon'), ('novel', 'Novel'), ('fanfic', 'Fanfic'), ('other', 'Outro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='newbook',
            name='format',
            field=models.CharField(choices=[('physical', 'Físico'), ('digital', 'Digital')], max_length=10),
        ),
        migrations.AlterField(
            model_name='newbook',
            name='publication_status',
            field=models.CharField(choices=[('completed', 'Completa'), ('ongoing', 'Em lançamento'), ('hiatus', 'Em hiato')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='newbook',
            name='status',
            field=models.CharField(choices=[('want_to_read', 'Quero ler'), ('reading', 'Lendo'), ('finished', 'Terminado')], default='want_to_read', max_length=20),
        ),
    ]
