# Generated by Django 5.2.18 on 2026-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTrack', '0005_alter_newbook_content_type_alter_newbook_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newbook',
            name='status',
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='current_page',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
